### PR TITLE
transform dialog stack to self-destroying stack

### PR DESCRIPTION
**Pull request by jreidinger**
First part of code that demonstrate how to use wrapper around container holding pointers to prevent leaking memory and need to have Terminator.
Do not merge yet, but please discuss if it is right direction.
Especially for @anaseli and @mvidner to show what I have in mind with autodestructor instead of terminator.

### CODE REVIEW

**Comment by opensusegithubapi** [comment]
Can one of the admins verify this patch?

**Comment by mvidner** [comment]
Jenkins, ok to test.

**Comment by mvidner** [comment]
Jenkins-trigger-phrase
(sorry for the noise, testing automated PR building at https://ci.opensuse.org/view/libyui-staging/job/libyui-ghprb/ )

**Comment by mvidner** [comment]
Testing Jenkins GH PR Builder access

**Comment by mvidner** [comment]
Jenkins, ok to test.

**Comment by mvidner** [comment]
Jenkins-trigger-phrase

**Comment by mvidner** [comment]
Jenkins-trigger-phrase

**Comment by mvidner** [comment]
ok to test

**Comment by besser82** [comment]
Any progress on this?  Before this PR gets merged, it should be rebased onto recent master-branch and it should bump major-so-name and at least minor-version…

**Comment by timofonic** [comment]
@jreidinger @anaselli @mvidner @opensusegithubapi @besser82 @shundhammer @lslezak @rwx788 @AdamMajer Any news about this? I would love to see more progress on this library and more tools be based on it, so they could provide TUI and GUI interfaces. I found it quite interesting for different use-bases.

Are there any interest?

**Comment by rwx788** [comment]
@timofonic I guess it's still considered as nice to have, so don't really expect it to be completed soon, but some time in the future.

**Comment by shundhammer** [comment]
See also https://bugzilla.suse.com/show_bug.cgi?id=1074596 (parts not visible to outside of SUSE, sorry for that)

**Pull request closed without merging**
